# Generated by Django 2.1.4 on 2019-04-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcustomer',
            old_name='allmoney',
            new_name='u_name',
        ),
        migrations.RemoveField(
            model_name='addcustomer',
            name='u_nam',
        ),
    ]
